### ISSUE TITLE
InterpretApplication failed to join multiple multicast groups

### ISSUE THREAD

**Issue by achilleswu** [objectcomputing/quickfast#131]
Hi, All,

I am trying to use InterpretApplication to join multiple multicase groups, but failed.
I can join any one of these two multicast groups without problem.

Maybe I misunderstand the command line configurations, please correct me if I am wrong.

I am calling it by:
./InterpretApplication -t xxx.xml -mname A -multicast 224.a.b.c:5000 -mname b -multicast 224.a.b.d:5001

Seems the problem is in src/Application/DecoderConfiguration.h

 void setMulticastGroupIP(const std::string & multicastGroupIP)
      {
        needMulticastFeed();
        multicastFeeds_[0].groupIP_ = multicastGroupIP;
      }

This one will always set the multicast group to index 0. I guess this should be set to the last one pushed in.

 multicastFeeds_.back().groupIP_ = multicastGroupIP;

Same thing applies to other places.

**Comment by achilleswu** [comment]
Hmm.. After above fix, from tcp dump, I can see I have packets from both streams. But 
QuickFAST::Communication::MulticastReceiver::MulticastFeed::handleReceive is never called.
It just stuck in epoll_wait

(gdb) bt
#0  0x000000320f0e8e63 in epoll_wait () from /lib64/libc.so.6
#1  0x0000000000463124 in boost::asio::detail::epoll_reactor::run ()
#2  0x00000000004638f9 in QuickFAST::Communication::AsioService::run() ()
#3  0x00000000004642af in QuickFAST::Communication::AsioService::runThreads(unsigned long, bool) ()
#4  0x000000000041a89f in QuickFAST::Examples::InterpretApplication::run (this=0x7fffffffe2f0)

But from captured tcpdump, I see traffic coming.

Any idea?
Thanks

**Comment by achilleswu** [comment]
Update, seems the problem is that I give multiple multicast feed the same listen address. -mlisten
once I change the listen address to 0.0.0.0, the issue is resolved.
